### PR TITLE
Add run exports for library

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@pkgw

**Comment by ehfd** [comment]
@pkgw Can this be approved? This is the same as last time.

**Comment by ehfd** [comment]
@pkgw

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@hmaarrfk Can we merge this?

**Comment by hmaarrfk** [comment]
Let's give the maintainer (pkgw) time to weigh in. 

I don't really know the X11 stack too well..

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> Let's give the maintainer (pkgw) time to weigh in.

This PR was opened in May; if there's no response until June (much less July), I think we have to move on. Many (all?) of the other xorg-libs have run-exports, as they should, so let's add it here as well (also, `libxtst` [contains](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fxorg-libxtst-1.2.3-h7f98852_1002.tar.bz2) a shared library, not just headers).

Thanks for the PR @ehfd, and especially for volunteering to help out with the recipe! 🙏

**Review by h-vetinari — APPROVED** [review]

**Comment by hmaarrfk** [comment]
> This PR was opened in May; if there's no response until June (much less July), I think we have to move on. Many (all?) of the other xorg-libs have run-exports, as they should, so let's add it here as well (also, libxtst [contains](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fxorg-libxtst-1.2.3-h7f98852_1002.tar.bz2) a shared library, not just headers).

Thanks for the deep dive!

**Pull request merged**
